server:
  port: 8087
  servlet:
    context-path: /mall-admin

spring:
  datasource:
   username: root
   password: '123456'
   url: jdbc:mysql://127.0.0.1:3306/wd-mall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
   driver-class-name: com.mysql.cj.jdbc.Driver
   druid:
     initial-size: 3          #初始化时建立物理连接的个数
     min-idle: 3               #最小连接池数量
     max-active: 10            #最大连接池数量
     max-wait: 600000          #获取连接时最大等待时间
     stat-view-servlet:
       login-username: admin  #配置监控页面访问登录名称
       login-password: admin  #配置监控页面访问密码
     filter:
       stat:
         log-slow-sql: true   #是否开启慢sql查询监控
         slow-sql-millis: 1  #慢SQL执行时间
  redis:
    database: 0
    host: 192.168.0.46
    port: 6379
    password: '##!zggc5055'
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
    lettuce:
      pool:
        max-active: 8
        min-idle: 8
  jackson:
    default-property-inclusion: non_null

mybatis:
  type-aliases-package: com.bc.wd.entity
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
   com.whl.demo.mapper: debug
  config: classpath:log4j2.xml

security:
  secret: token  #秘钥

token:
  tokenExpireTime: 30 #令牌有效期分钟